### PR TITLE
added zoom hooks, separated css, added help stub, added dialogs,...

### PR DESCRIPTION
**Pull request by bmames00**
reorganized mainwindow.js. One dialog remains to be created. Actions taken for menus and buttons are not all correct.

### CODE REVIEW

**Comment by alexlib** [comment]
on Mac OS X on both Chrome and Safari it looks a bit strange, maybe something with the fonts  (menu is smaller than the font in the buttons in the windows) - we need to think about some CSS. Can we adopt some kind of a standard CSS template that looks uniform? 

Otherwise, the UI is very responsive and pleasant.

**Comment by bmames00** [comment]
The font sizes vary from place to place between 10pt and 11pt, whatever 
allowed the text to fit. Ideally, the font sizes would be placed in a 
new style sheet, say openpiv.css, which would be specified by class 
rather than id as in mainwindow.css. To allow for that, I passed in the 
Qt widget class when I generated the initial html. The widget classes 
don't necessarily properly classify our UI but they should be very close.


On 03/20/2015 03:48 AM, Alex Liberzon wrote:
>
> on Mac OS X on both Chrome and Safari it looks a bit strange, maybe 
> something with the fonts (menu is smaller than the font in the buttons 
> in the windows) - we need to think about some CSS. Can we adopt some 
> kind of a standard CSS template that looks uniform?
>
> Otherwise, the UI is very responsive and pleasant.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenPIV/jQueryUI/pull/2#issuecomment-83944537>.
>


-- 
Best regards,

Brian M. Ames

**Comment by alexlib** [comment]
it still looks the same, at least on my browsers.

**Comment by alexlib** [comment]
It also seems to be that mainwindow.html doubles the code which appears also in fliterwindow and other sub-windows. is it correct? 
e.g. when I press setup - I see some things from the filterwindow and I think it's from the mainwindow

**Comment by bmames00** [comment]
I have some more changes in the CSS that should fix that. My previous
change seemed tobreak all the check boxes due to a missing closing double
quote.

**Comment by alexlib** [comment]
looks much better now. can you please, take a look on the size of the tabs in Setup window - the image mask is under correlation tab and not clickable. I think the window shall be larger in horizontal and have all the tabs in one line. 
thanks

**Comment by alexlib** [comment]
can we also please, replace the logo with this one: 

http://www.openpiv.net/images/openpiv_arrow.png

**Comment by bmames00** [comment]
Logo changed and setup dialog widened.

**Comment by alexlib** [comment]
made two small fixes - sent you my pull request.

**Comment by alexlib** [comment]
see

https://github.com/bmames00/jQueryUI/pull/1

**Pull request merged**
